export type HttpMethod = "GET" | "POST" | "PATCH" | "DELETE";

export type EndpointDefinition = {
  id: string;
  group: string;
  name: string;
  method: HttpMethod;
  path: string;
  auth?: "Public" | "Session" | "Candidate" | "Recruiter" | "Admin";
  description: string;
  params?: Record<string, string>;
  query?: Record<string, string>;
  body?: Record<string, unknown>;
};

export const apiGroups = [
  "System",
  "Auth",
  "Users",
  "Jobs",
  "Companies",
  "Categories",
  "Skills",
  "Applications",
  "Saved Jobs",
  "Notifications",
  "Dashboard",
];

export const endpoints: EndpointDefinition[] = [
  {
    id: "system-health",
    group: "System",
    name: "Health check",
    method: "GET",
    path: "/",
    auth: "Public",
    description: "Reads the root application response.",
  },
  {
    id: "auth-login",
    group: "Auth",
    name: "Login",
    method: "POST",
    path: "/auth/login",
    auth: "Public",
    description: "Creates an HTTP-only access_token cookie.",
    body: { email: "john@example.com", password: "password123" },
  },
  {
    id: "auth-register-candidate",
    group: "Auth",
    name: "Register candidate",
    method: "POST",
    path: "/auth/register/candidate",
    auth: "Public",
    description: "Creates a candidate account.",
    body: {
      email: "candidate@example.com",
      password: "password123",
      firstName: "Aarav",
      lastName: "Mehta",
    },
  },
  {
    id: "auth-register-recruiter",
    group: "Auth",
    name: "Register recruiter",
    method: "POST",
    path: "/auth/register/recruiter",
    auth: "Public",
    description: "Creates a recruiter account.",
    body: {
      email: "recruiter@example.com",
      password: "password123",
      firstName: "Priya",
      lastName: "Shah",
    },
  },
  {
    id: "auth-me",
    group: "Auth",
    name: "Current user",
    method: "GET",
    path: "/auth/me",
    auth: "Session",
    description: "Returns the currently logged-in user.",
  },
  {
    id: "users-create",
    group: "Users",
    name: "Create user",
    method: "POST",
    path: "/users",
    auth: "Public",
    description: "Creates a user directly with a selected role.",
    body: {
      email: "admin@example.com",
      password: "password123",
      firstName: "Admin",
      lastName: "User",
      role: "admin",
    },
  },
  {
    id: "users-all",
    group: "Users",
    name: "List users",
    method: "GET",
    path: "/users",
    auth: "Admin",
    description: "Lists all users.",
  },
  {
    id: "users-profile",
    group: "Users",
    name: "My profile",
    method: "GET",
    path: "/users/profile",
    auth: "Session",
    description: "Reads the logged-in user's profile.",
  },
  {
    id: "users-update-profile",
    group: "Users",
    name: "Update profile",
    method: "PATCH",
    path: "/users/profile",
    auth: "Session",
    description: "Updates profile names and optional asset URLs.",
    body: {
      firstName: "Aarav",
      lastName: "Mehta",
      avatarUrl: "https://example.com/avatar.png",
      resumeUrl: "https://example.com/resume.pdf",
    },
  },
  {
    id: "users-change-password",
    group: "Users",
    name: "Change password",
    method: "PATCH",
    path: "/users/profile/change-password",
    auth: "Session",
    description: "Changes the current user's password.",
    body: { currentPassword: "password123", newPassword: "newpassword123" },
  },
  {
    id: "users-avatar",
    group: "Users",
    name: "Update avatar",
    method: "PATCH",
    path: "/users/profile/avatar",
    auth: "Session",
    description: "Updates only avatarUrl.",
    body: { avatarUrl: "https://example.com/avatar.png" },
  },
  {
    id: "users-resume",
    group: "Users",
    name: "Update resume",
    method: "PATCH",
    path: "/users/profile/resume",
    auth: "Session",
    description: "Updates only resumeUrl.",
    body: { resumeUrl: "https://example.com/resume.pdf" },
  },
  {
    id: "users-one",
    group: "Users",
    name: "Get user",
    method: "GET",
    path: "/users/:id",
    auth: "Public",
    description: "Reads a user by id.",
    params: { id: "user-uuid" },
  },
  {
    id: "users-update",
    group: "Users",
    name: "Update user",
    method: "PATCH",
    path: "/users/:id",
    auth: "Public",
    description: "Updates a user by id.",
    params: { id: "user-uuid" },
    body: { firstName: "Updated", lastName: "User", role: "candidate" },
  },
  {
    id: "users-delete",
    group: "Users",
    name: "Delete user",
    method: "DELETE",
    path: "/users/:id",
    auth: "Public",
    description: "Deletes a user by id.",
    params: { id: "user-uuid" },
  },
  {
    id: "jobs-create",
    group: "Jobs",
    name: "Create job",
    method: "POST",
    path: "/jobs",
    auth: "Recruiter",
    description: "Creates a job for the logged-in recruiter.",
    body: {
      title: "Frontend Engineer",
      description: "Build modern product interfaces.",
      type: "full_time",
      location: "Bengaluru",
      isRemote: true,
      salaryMin: 1200000,
      salaryMax: 2400000,
      expiresAt: "2026-12-31T00:00:00.000Z",
      companyId: "company-uuid",
      categoryId: "category-uuid",
      skillIds: ["skill-uuid"],
    },
  },
  {
    id: "jobs-all",
    group: "Jobs",
    name: "List jobs",
    method: "GET",
    path: "/jobs",
    auth: "Public",
    description: "Lists jobs with pagination and filters.",
    query: {
      page: "1",
      limit: "10",
      search: "",
      status: "published",
      type: "full_time",
      categoryId: "",
      isRemote: "",
    },
  },
  {
    id: "jobs-one",
    group: "Jobs",
    name: "Get job",
    method: "GET",
    path: "/jobs/:id",
    auth: "Public",
    description: "Reads one job by id.",
    params: { id: "job-uuid" },
  },
  {
    id: "jobs-update",
    group: "Jobs",
    name: "Update job",
    method: "PATCH",
    path: "/jobs/:id",
    auth: "Session",
    description: "Updates a job owned by the logged-in recruiter.",
    params: { id: "job-uuid" },
    body: { title: "Updated Frontend Engineer", salaryMax: 2600000 },
  },
  {
    id: "jobs-publish",
    group: "Jobs",
    name: "Publish job",
    method: "PATCH",
    path: "/jobs/:id/publish",
    auth: "Session",
    description: "Publishes a recruiter-owned job.",
    params: { id: "job-uuid" },
  },
  {
    id: "jobs-close",
    group: "Jobs",
    name: "Close job",
    method: "PATCH",
    path: "/jobs/:id/close",
    auth: "Session",
    description: "Closes a recruiter-owned job.",
    params: { id: "job-uuid" },
  },
  {
    id: "jobs-delete",
    group: "Jobs",
    name: "Delete job",
    method: "DELETE",
    path: "/jobs/:id",
    auth: "Session",
    description: "Deletes a recruiter-owned job.",
    params: { id: "job-uuid" },
  },
  {
    id: "companies-create",
    group: "Companies",
    name: "Create company",
    method: "POST",
    path: "/companies",
    auth: "Recruiter",
    description: "Creates a company for the logged-in recruiter.",
    body: {
      name: "NovaHire Labs",
      description: "A product engineering company.",
      website: "https://example.com",
      logoUrl: "https://example.com/logo.png",
      location: "Bengaluru",
      size: "startup",
    },
  },
  {
    id: "companies-all",
    group: "Companies",
    name: "List companies",
    method: "GET",
    path: "/companies",
    auth: "Public",
    description: "Lists companies with pagination.",
    query: { page: "1", limit: "10" },
  },
  {
    id: "companies-mine",
    group: "Companies",
    name: "My companies",
    method: "GET",
    path: "/companies/my-companies",
    auth: "Recruiter",
    description: "Lists companies owned by the logged-in recruiter.",
  },
  {
    id: "companies-one",
    group: "Companies",
    name: "Get company",
    method: "GET",
    path: "/companies/:id",
    auth: "Public",
    description: "Reads one company by id.",
    params: { id: "company-uuid" },
  },
  {
    id: "companies-update",
    group: "Companies",
    name: "Update company",
    method: "PATCH",
    path: "/companies/:id",
    auth: "Session",
    description: "Updates a company.",
    params: { id: "company-uuid" },
    body: { name: "NovaHire Labs Updated", size: "medium" },
  },
  {
    id: "companies-verify",
    group: "Companies",
    name: "Verify company",
    method: "PATCH",
    path: "/companies/:id/verify",
    auth: "Admin",
    description: "Marks a company as verified.",
    params: { id: "company-uuid" },
  },
  {
    id: "companies-delete",
    group: "Companies",
    name: "Delete company",
    method: "DELETE",
    path: "/companies/:id",
    auth: "Session",
    description: "Deletes a company.",
    params: { id: "company-uuid" },
  },
  {
    id: "categories-create",
    group: "Categories",
    name: "Create category",
    method: "POST",
    path: "/categories",
    auth: "Admin",
    description: "Creates a job category.",
    body: { name: "Software Engineering", icon: "code" },
  },
  {
    id: "categories-all",
    group: "Categories",
    name: "List categories",
    method: "GET",
    path: "/categories",
    auth: "Public",
    description: "Lists all categories.",
  },
  {
    id: "categories-one",
    group: "Categories",
    name: "Get category",
    method: "GET",
    path: "/categories/:id",
    auth: "Public",
    description: "Reads one category by id.",
    params: { id: "category-uuid" },
  },
  {
    id: "categories-update",
    group: "Categories",
    name: "Update category",
    method: "PATCH",
    path: "/categories/:id",
    auth: "Admin",
    description: "Updates a job category.",
    params: { id: "category-uuid" },
    body: { name: "Product Engineering", icon: "cpu" },
  },
  {
    id: "categories-delete",
    group: "Categories",
    name: "Delete category",
    method: "DELETE",
    path: "/categories/:id",
    auth: "Admin",
    description: "Deletes a job category.",
    params: { id: "category-uuid" },
  },
  {
    id: "skills-create",
    group: "Skills",
    name: "Create skill",
    method: "POST",
    path: "/skills",
    auth: "Admin",
    description: "Creates a skill.",
    body: { name: "NestJS" },
  },
  {
    id: "skills-all",
    group: "Skills",
    name: "List skills",
    method: "GET",
    path: "/skills",
    auth: "Public",
    description: "Lists all skills.",
  },
  {
    id: "skills-one",
    group: "Skills",
    name: "Get skill",
    method: "GET",
    path: "/skills/:id",
    auth: "Public",
    description: "Reads one skill by id.",
    params: { id: "skill-uuid" },
  },
  {
    id: "skills-update",
    group: "Skills",
    name: "Update skill",
    method: "PATCH",
    path: "/skills/:id",
    auth: "Admin",
    description: "Updates a skill.",
    params: { id: "skill-uuid" },
    body: { name: "Next.js" },
  },
  {
    id: "skills-delete",
    group: "Skills",
    name: "Delete skill",
    method: "DELETE",
    path: "/skills/:id",
    auth: "Admin",
    description: "Deletes a skill.",
    params: { id: "skill-uuid" },
  },
  {
    id: "applications-create",
    group: "Applications",
    name: "Apply to job",
    method: "POST",
    path: "/applications",
    auth: "Candidate",
    description: "Creates an application for the logged-in candidate.",
    body: {
      jobId: "job-uuid",
      coverLetter: "I am excited about this opportunity.",
      resumeUrl: "https://example.com/resume.pdf",
    },
  },
  {
    id: "applications-mine",
    group: "Applications",
    name: "My applications",
    method: "GET",
    path: "/applications/my",
    auth: "Candidate",
    description: "Lists applications for the logged-in candidate.",
  },
  {
    id: "applications-job",
    group: "Applications",
    name: "Job applications",
    method: "GET",
    path: "/applications/job/:jobId",
    auth: "Recruiter",
    description: "Lists applications for a recruiter's job.",
    params: { jobId: "job-uuid" },
  },
  {
    id: "applications-status",
    group: "Applications",
    name: "Update application status",
    method: "PATCH",
    path: "/applications/:id/status",
    auth: "Recruiter",
    description: "Updates an application status.",
    params: { id: "application-uuid" },
    body: { status: "reviewing" },
  },
  {
    id: "applications-delete",
    group: "Applications",
    name: "Withdraw application",
    method: "DELETE",
    path: "/applications/:id",
    auth: "Candidate",
    description: "Withdraws an application.",
    params: { id: "application-uuid" },
  },
  {
    id: "saved-jobs-create",
    group: "Saved Jobs",
    name: "Save job",
    method: "POST",
    path: "/saved-jobs",
    auth: "Candidate",
    description: "Saves a job for the logged-in candidate.",
    body: { jobId: "job-uuid" },
  },
  {
    id: "saved-jobs-all",
    group: "Saved Jobs",
    name: "My saved jobs",
    method: "GET",
    path: "/saved-jobs",
    auth: "Candidate",
    description: "Lists saved jobs for the logged-in candidate.",
  },
  {
    id: "saved-jobs-delete",
    group: "Saved Jobs",
    name: "Remove saved job",
    method: "DELETE",
    path: "/saved-jobs/:id",
    auth: "Candidate",
    description: "Removes a saved job record.",
    params: { id: "saved-job-uuid" },
  },
  {
    id: "notifications-all",
    group: "Notifications",
    name: "My notifications",
    method: "GET",
    path: "/notifications",
    auth: "Session",
    description: "Lists notifications for the logged-in user.",
    query: { page: "1", limit: "10" },
  },
  {
    id: "notifications-read-all",
    group: "Notifications",
    name: "Mark all read",
    method: "PATCH",
    path: "/notifications/read-all",
    auth: "Session",
    description: "Marks all notifications as read.",
  },
  {
    id: "notifications-read-one",
    group: "Notifications",
    name: "Mark notification read",
    method: "PATCH",
    path: "/notifications/:id/read",
    auth: "Session",
    description: "Marks one notification as read.",
    params: { id: "notification-uuid" },
  },
  {
    id: "dashboard",
    group: "Dashboard",
    name: "Role dashboard",
    method: "GET",
    path: "/dashboard",
    auth: "Session",
    description: "Returns candidate, recruiter, or admin dashboard data by role.",
  },
];
